### PR TITLE
Fix build and Dockerfile

### PR DESCRIPTION
**Pull request by zmstone**
The glide to mod migration has some dependency issue.
The `cli` lib should really be `v2` instead, otherwise it won't compile.
--- or maybe I did something wrong, please let me know if that's the case.

Also the latest burrow is on v3 api, that is why `ENV API_VERSION` is set to `3` in Dockerfile. 

Tested with:
```
docker build . -t burrow_exporter:test
```
```
docker run --rm --net host -it burrow_exporter:test ./burrow-exporter --burrow-addr=http://localhost:8082
INFO[0000] Scraping burrow...                            timestamp=1581008946640668824
INFO[0000] Finished scraping burrow.                     timestamp=1581008946647328652 took=6.660037ms
```

### CODE REVIEW

**Comment by zmstone** [comment]
it seems it doesn't work if merge with master.
did not notice the commit 477f4ad435be4509f16cb0bac386fe72da3fd58d

**Comment by zmstone** [comment]
@rjh-yext would it be possible to revert 477f4ad435be4509f16cb0bac386fe72da3fd58d and merge this instead ? i.e. use `cli/v2`

**Comment by zmstone** [comment]
alright. resolved conflict again.

**Comment by JensRantil** [comment]
@rjh-yext Anything outstanding here?

**Pull request closed without merging**
